
spring.application.name=gradle


spring.cloud.gcp.project-id=decisive-lambda-431906-k9
spring.cloud.gcp.spanner.instance-id=spanner-demo1
spring.cloud.gcp.spanner.database=employee


spring.cloud.gcp.credentials.location=file:/C:/decisive-lambda-431906-k9-2bbd40965de0.json

